Owl next new rendering
odoo/owl pull request #998
Opened 2021-11-24 12:09 UTC by ged-odoo

2022-01-21 09:11 UTC, sdegueldre requested changes

2022-02-24 14:29 UTC, ged-odoo commented on src/app/template_helpers.ts
> +  const slots = nonReactiveProps ? nonReactiveProps.slots || {} : {};
should markraw at the source instead

2022-02-24 14:32 UTC, ged-odoo commented on src/component/component.ts
> +  render(force: boolean = false) {
rename to deep

2022-02-24 14:39 UTC, ged-odoo commented on src/component/component_node.ts
> +    props = useState(props);
or somewher else

2022-02-24 14:41 UTC, ged-odoo commented on src/component/component_node.ts
> +    props = useState(props);
check if we should clearreactivecallbacks for old props

2022-02-24 14:42 UTC, ged-odoo commented on src/component/component_node.ts
> +  _patch() {
maybe remove _patch

2022-02-24 14:46 UTC, ged-odoo commented on tests/components/basics.test.ts
> +        expect(this.props).not.toBe(p);
toRaw

2022-02-24 14:56 UTC, ged-odoo commented on src/compiler/code_generator.ts
> -      props.push(`slots: ${slotDef}`);
remove target toraw from callslot helper

2022-02-25 09:25 UTC, sdegueldre approved these changes

2022-02-25 09:32 UTC, merged